import assert from "node:assert/strict"
import path from "node:path"
import { terminal } from "./terminal.ts"
import type { fixture } from "./host-fixture.ts"
import type { Controller } from "../src/controller.ts"

export async function verifyInspector(test: Awaited<ReturnType<typeof fixture>>, controller: Controller, executable: string) {
  const output = path.join(test.root, "inspector-tui.log")
  const child = terminal({ executable, url: test.url, project: test.project, sessionID: controller.sessionID, env: test.env, output })
  const sleep = () => new Promise((resolve) => setTimeout(resolve, 250))
  const keys = async (keys: string) => { child.keys(keys); await sleep() }
  const seen = (text: string) => test.until(async () => (await child.text()).includes(text), `inspector UI: ${text}`)
  try {
    await seen("Context manager production sm")
    const before = test.requests.length
    await keys("/context-manager")
    await keys("\r")
    await seen("Local text")
    await seen("Ready.")
    await seen("Overview")
    assert.ok(!(await child.text()).includes("Runtime inventory"))
    await keys("v")
    await seen("LOCAL CONTEXT")
    await keys("v")
    await seen("Content")
    await keys("v")
    await seen("Runtime")
    await keys("v")
    await seen("Overview")
    assert.equal(test.requests.length, before)
    await keys(" ")
    await keys(" ")
    await keys("c")
    await seen("Compaction configuration")
    await keys("\x1b[H")
    await keys(" ")
    await keys("\r")
    await test.until(async () => (await controller.load()).policy.operations.at(-1)?.mode === "prune-reason", "UI reasoning prune")
    const revision = (await controller.load()).policy.revision
    await keys("\x10")
    await keys("c")
    await keys("\x1b")
    assert.equal((await controller.load()).policy.revision, revision)
    await keys("\r")
    await seen("Turn reader")
    await keys("\x1b")
    await keys("c")
    await keys("\x1b[H")
    for (let n = 0; n < 4; n++) await keys("\x1b[B")
    await keys(" ")
    await keys("\r")
    await test.until(async () => (await controller.load()).policy.operations.at(-1)?.mode === "compact", "UI summary application")
    await seen("Summaries applied automatically")
    await keys("\r")
    await seen("Summary reader")
    await keys("r")
    await keys("Clarify the saved summary")
    const beforeEdit = (await controller.load()).policy.revision
    await keys("\x13")
    await seen("EDIT_ONE")
    assert.equal((await controller.load()).policy.revision, beforeEdit)
    await keys("\x13")
    await test.until(async () => (await controller.load()).policy.operations.at(-1)?.mode === "revise", "UI explicit summary revision")
    await keys("\x1b")
    await keys("\x05")
    await seen("Restore preview")
    await keys("\x13")
    await test.until(async () => (await controller.load()).policy.operations.at(-1)?.mode === "expand", "UI summary expansion")
    const loaded = await controller.load()
    assert.equal(loaded.blocks[0].reasonPruned, true)
    const beforeRestore = test.requests.length
    await keys("\x05")
    await seen("1 pruning")
    await keys("\x13")
    await test.until(async () => !(await controller.load()).blocks[0].reasonPruned, "UI pruning restoration")
    assert.equal(test.requests.length, beforeRestore, "UI pruning restoration must not invoke a model")
    child.resize(100, 30)
    await sleep()
    child.resize(80, 24)
    await sleep()
    await keys("\x1b")
  } finally {
    assert.equal(await child.close(), 0, "Owned TUI must stop cleanly")
  }
}
